import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar/Navbar'
import styles from '../styles/Home.module.css'
import { signIn, signOut, useSession } from 'next-auth/react'



const Home: NextPage = () => {
  const {data, status} = useSession()
  console.log('data: ', data, 'status:', status)

  if(status === 'loading'){
    return <h1>loading buddy</h1>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar/> */}

      <main className={styles.main}>
       
        <h1 className={styles.title}>
        </h1>
          {
            data === null ? 
            <>
                      Welcome Guest

              <button className='signIn' onClick={()=> signIn()} >Giriş yap</button>
            </> : <>
            <div style={ {textAlign: 'center'} }>
               Welcome <br/> {data.user?.name}
            </div>
             <button className='signout signIn' onClick={()=> signOut()}> Çıkış yap</button>
           
            </>
          }
       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
